### ISSUE TITLE
Add optional ResourceName parameter to ElasticBeanstalk OptionSetting

### ISSUE THREAD

**Issue by mcamou** [MonsantoCo/cloudformation-template-generator#192]
An `OptionSetting` in an `AWS::ElasticBeanstalk::ConfigurationTemplate` has an optional `ResourceName` parameter, which can be used to pass options to the underlying elements (i.e., the Elastic Load Balancer). For example:

```yaml
Resources:
  ElasticBeanstalkTest:
    Type: "AWS::ElasticBeanstalk::ConfigurationTemplate"
    Properties:
        - Namespace: "aws:elb:listener:4222"
          ResourceName: AWSEBLoadBalancer
          OptionName: ListenerProtocol
          Value: TCP
```

The `com.monsanto.arch.cloudformation.model.resource.OptionSetting` class only supports the `Namespace`,  `OptionName` and `Value` parameters, but not the optional `ResourceName`.
